---
title: ""
date: "As of `r Sys.Date()`"
output:
  html_document:
    theme: spacelab
---

<style>
.main-container {
    width: 100%;
    max-width: unset;
}
</style>

```{r setup, include=FALSE, warning=F, message=F}
library(tidyverse)
library(DT)
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r, include=FALSE, eval=FALSE}
library(peekbankr)

## create datatable
datasets <- peekbankr::get_datasets()
admins <- peekbankr::get_administrations()
subjects <- peekbankr::get_subjects()
dataset_info <- left_join(subjects, admins) %>%
  left_join(datasets) %>%
  group_by(dataset_name, cite) %>%
  summarise(n = length(unique(subject_id)), 
            min_age_months = min(age, na.rm = TRUE), 
            max_age_months = max(age, na.rm = TRUE)) #%>%
  # mutate(cite = str_replace_all(cite, "\\x96", "–"))
saveRDS(dataset_info, "dataset_info.Rds")
```

```{r datatable}
dataset_info <- readRDS("dataset_info.Rds")
pretty_names <- colnames(dataset_info) %>%
  str_replace_all("_", " ") %>%
  str_to_sentence()
DT::datatable(dataset_info, colnames = pretty_names, rownames = FALSE,
              width = "100%", style = "bootstrap",
              options = list(pageLength = 10,lengthMenu = c(5, 10, 15, 20)))
```

